version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: zwembad_db
    restart: always
    environment:
      MYSQL_DATABASE: zwembad_status
      MYSQL_ROOT_PASSWORD: geheim_wachtwoord
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: zwembad_web
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229" # Debug poort
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=geheim_wachtwoord
      - DB_NAME=zwembad_status
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  db_data:
